### ISSUE TITLE
Issue: Search function not working

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#13]
I received the following error message when trying to use the Search function from within the dependency:
```
ERROR: TypeError: Cannot read properties of undefined (reading 'attribs')
    at classNames ([e:\Users\Phil\Documents\github\furexplicitbot\node_modules\furaffinity-api\dist\Parser.js:33:20]())
    at Object.ParseSearchPaging ([e:\Users\Phil\Documents\github\furexplicitbot\node_modules\furaffinity-api\dist\Parser.js:143:10]())
    at [e:\Users\Phil\Documents\github\furexplicitbot\node_modules\furaffinity-api\dist\index.js:39:25]()
    at Generator.next (<anonymous>)
    at fulfilled ([e:\Users\Phil\Documents\github\furexplicitbot\node_modules\furaffinity-api\dist\index.js:15:58]())
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: Cannot read properties of undefine…ions (node:internal/process/task_queues:96:5)', message: 'Cannot read properties of undefined (reading 'attribs')'}
```

the code I was trying to run (discord.js bot):
```JS
module.exports.run = async (interaction) => {
  if (!DEBUG) await interaction.deferReply();
  const query = interaction.options.getString('search', true);
  const ammoumt = interaction.options.getNumber('ammount', false) || 1;
  if (ammoumt > 24) return messageFail(interaction, uwu('You can only request a maximum of ßß24 images at the time.'), null, true);
  const rating = interaction.channel.nsfw ? 7 : 1;
  const pics = await Search(query, { perpage: 24, rating });
  pics.reverse().slice(-ammoumt).forEach(async (submission, i) => {
    const embed = prepareMessage(submission);
    const message = await reply(interaction, { embeds: [embed], components: [buttons], fetchReply: true }, i);
    buttonHandler(message, interaction, embed);
  });
};
```

While debugging, everything was set correctly for the Search function. Let me know if I should test additional things.

**Comment by phil-flip** [comment]
The code can also be viewed completely here.
https://github.com/FlippedCodes/furexplicitbot/blob/dev/commands/furaffinity/search.js
And is called by
https://github.com/FlippedCodes/furexplicitbot/blob/dev/commands/furaffinity.js

**Comment by recallfuture** [comment]
It doesn't look like the fa was modified, my tests are working fine, so I have 2 questions:
1. Is this user using **modern** theme or not?
2. Can you provide the search parameters for the error?

**Comment by recallfuture** [comment]
By the way, I found perpage(24/48/72) can working with search, so next version it will be added together.

**Comment by phil-flip** [comment]
Modern design is used

![image](https://user-images.githubusercontent.com/27019397/164222944-7a2f17e6-3754-495f-95f6-d8ba8ea260ee.png)

but it will always do `perpage: 24` even if the amount is different (as otherwise it defaults to 48, which would be too many unneeded posts)

and for a search it doesn't matter what i put in

**Comment by recallfuture** [comment]
Those two buttons are use to get prev/next link, and seems like not available at your place, so it throw an error.

![image](https://user-images.githubusercontent.com/29711565/164227425-ab571766-15c7-495f-96d8-432cd1efe167.png)

You can check if these two buttons exist.

**Comment by phil-flip** [comment]
They do exist

**Comment by recallfuture** [comment]
Well, that not make sense, can you replace your code with the following down there? I guess response body can explain everything

```ts
import { FetchSearch } from "furaffinity-api/dist/Request";
const body = await FetchSearch("vore", { perpage: 24, rating });
```

**Comment by phil-flip** [comment]
without login:
```ts
import { FetchSearch } from 'furaffinity-api/dist/Request';

import fs from 'fs';

async function main() {
  const outp = await FetchSearch('vore', { rating: 7 });
  await fs.writeFileSync('./outp.html', outp);
}

main();
```
i get https://www.toptal.com/developers/hastebin/edewavolik.xml


and with login:
```ts
import { Login } from 'furaffinity-api';

import { FetchSearch } from 'furaffinity-api/dist/Request';

import fs from 'fs';

async function main() {
  await Login(process.env.FACookieA, process.env.FACookieB);
  const outp = await FetchSearch('vore', { rating: 7 });
  await fs.writeFileSync('./outp.html', outp);
}

main();

```
i get: https://www.toptal.com/developers/hastebin/ayamuruvaf.xml


mind, that I tested that on another program with import/export
on my discord bot, if i use the login function, it breaks… otherwise, it does work, when not logged in on the original code

**Comment by phil-flip** [comment]
I also debugged it in my Bot at line
https://github.com/recallfuture/furaffinity-api/blob/874895710f65ce7a40b7af73934d0a7d48d46799/src/index.ts#L17
before it forwards to the parser
https://www.toptal.com/developers/hastebin/worubalubu.xml

**Comment by recallfuture** [comment]
> I also debugged it in my Bot at line
> 
> https://github.com/recallfuture/furaffinity-api/blob/874895710f65ce7a40b7af73934d0a7d48d46799/src/index.ts#L17
> 
> 
> before it forwards to the parser
> https://www.toptal.com/developers/hastebin/worubalubu.xml

Well, your bot' account is indeed using classic design, you can see that on [line 48](https://www.toptal.com/developers/hastebin/worubalubu.xml)

**Comment by phil-flip** [comment]
And you are totally right! After comparing the tokens, they are indeed from a different account. I remembered that I made a dedicated account for bot activity to not get my main account blocked. But I was sure it was using the modern one ^^'
So yes, sorry about that it works not without any issues, and thank you very much for your support :3
