### ISSUE TITLE
[Bug] Rating in SearchOption doesn't work

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#14]
I have some issues getting the rating to work... It also doesn't seem to work in the recent function.

I'm importing `Rating` and use `Rating.General` but it always gives me all results.

**Comment by recallfuture** [comment]
fixed in 4.4.1

FA suddenly treats the undefined values in the form as valid, that makes rating option turn to all.
So I cleaned up all the undefined values, now it works!
