### ISSUE TITLE
[Bug] Not parsing correctly 

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#15]
Hey,
I noticed, 2 little parsing issues with the "Author" function:
1. The first letter of the Description (Name/ID) get cut off as seen in the picture. It's supposed to say "Draws da pixels".
2. The Name and ID are the same. Not sure if that is intended, but I wanted to point that out as well ^^

![image](https://user-images.githubusercontent.com/27019397/177047967-c3d8f287-ee04-47eb-be27-f74f498a4b24.png)

Thank you by the way for this amazing dependency. It makes it so much easier to automate stuff from FA. A shame that they still don't implement a proper API and hold on to it, not doing so.
Keep up the good work ^^

**Comment by phil-flip** [comment]
Oh.. i just noticed that it's also affecting the URL.

**Comment by recallfuture** [comment]
When FA changed it's HTML, the functionality of this package may be affected, but I can't notice that change quickly.

So Thanks for all your issues, that helps a lot!

**Comment by recallfuture** [comment]
Fixed in 4.4.2

**Comment by phil-flip** [comment]
I know the pain of webscraping. i have been there with the same dependency from insert. But it was eventually so broken, i stopped using it
