### ISSUE TITLE
FA Website redesign

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#16]
Hello! I'm sorry to let you know that FA changed stuff about their website layout, breaking some endpoints

**Comment by recallfuture** [comment]
I found three API was broken, Author, User and MyWatchingList, is that all?

**Comment by recallfuture** [comment]
furaffinity-api@4.4.3 published, try it out!

**Comment by phil-flip** [comment]
My downloader script was failing at getting the amount of submissions from the artist page. But everything seems to work now again.
Thank you for the very quick fix.
