### ISSUE TITLE
[Suggestion] Watch and unwatch artists

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#17]
Would it be possible to add functionality to watch and unwatch artists?

**Comment by recallfuture** [comment]
Okey, I'll add it soon

**Comment by recallfuture** [comment]
v4.5.0 is release!

**Comment by phil-flip** [comment]
Thank you for the implantation and the release! I really appreciate it ^^

**Comment by phil-flip** [comment]
Funnily enough, the URL security codes are always the same for each artist… So I suspect it's a SHA1 hash. I tried for a hot minute to get what it represents, but I wasn't able to do so and eventually gave up and just get the author details and get the link that way.

**Comment by recallfuture** [comment]
Since it's called security code, maybe it's sha1 after adding salt, so let's just get it the easier way^^
