### ISSUE TITLE
Search page selection doesn't work, always returns first page

### ISSUE THREAD

**Issue by penbob3** [recallfuture/furaffinity-api#3]
Even if I hard code the page number within the module, it still returns the same set of posts when searching with a different page number. Not sure if this ever worked or if a change to the Furaffinity search system broke it, but it returns with no error and identical posts every time.

**Comment by recallfuture** [comment]
Fixed in 3.5.1, thx for the feedback!

changelog: 
- Use "Connection: Keep-Alive" to improve speed.
- [#3](https://github.com/recallfuture/furaffinity-api/issues/3) Fix SearchOptions and BrowserOptions doesn't work.
