### ISSUE TITLE
Rating SearchOption doesn't work

### ISSUE THREAD

**Issue by onegen-dev** [recallfuture/furaffinity-api#6]
I am trying to create a search command, however the rating search option somehow doesn't work.

```javascript
var query = "@lower hun" // for test, an artist that draws a lot of Mature/Explicit, which should be filtered
Search(query, { page: 1, rating: 1 })
	.then(res => {
		// function that displays the images
	});
```

This search will return even artworks which are Mature or Adult. It follows the query and also the page option correctly. I tried putting `"General"`, `'1'`, `Rating.General` or just `1`, but nothing worked.
EDIT: Type option doesn't work either.

**Comment by recallfuture** [comment]
v4.1.0 has fixed this!
