### ISSUE TITLE
Feature request: Being able to remove submissions

### ISSUE THREAD

**Issue by phil-flip** [recallfuture/furaffinity-api#8]
FurAffinity NOC for Android allows removing individual posts from the submission inbox.
Sadly, their code for the App is closed source, because I was hoping to provide insight to how that is done.

It would be great to have a function in a post element, to remove it from the submission box.

**Comment by recallfuture** [comment]
You can GET or POST `https://www.furaffinity.net/msg/submissions/new@72/` with params

for GET:
submissions%5B%5D=id1&submissions%5B%5D=id2&messagecenter-action=remove_checked

for POST:
submissions[]: id1
submissions[]: id2
messagecenter-action: remove_checked

`id1` and `id2` is submission id which you want remove.

I will provide this with a new help function later

**Comment by phil-flip** [comment]
Alright, thank you ^^

**Comment by phil-flip** [comment]
But I'm guessing the post which needs to be deleted needs to be on the same page?

**Comment by recallfuture** [comment]
It don't need, you can set any id you want, even not in inbox(will no effect)
